<template>
    <v-container>
    <v-card class="flex flex-column justify-space-between">
      <v-img height="200px"
        src="https://marketplace.canva.com/EAFyFtMdX-A/1/0/1131w/canva-minimalist-black-and-white-blank-paper-document-7yCmM-i8WLc.jpg"></v-img>
      <v-card-title>
        <span class="text-h5">Exam Name</span>
        <v-spacer></v-spacer>
      </v-card-title>

      <v-card-subtitle>
        Tags : d
      </v-card-subtitle>

      <v-card-actions>
        <v-btn color="orange-lighten-2" variant="text">
          Download
        </v-btn>

      </v-card-actions>

    </v-card>
  </v-container>
</template>
