name: 'Setup .NET environment'
description: 'Sets up .NET with nuget dependency caching, restores and builds'
inputs:
  global-json-file:
    description: 'Path to global json file'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ${{ inputs.global-json-file }}

    - name: Set up nuget dependency caching for faster builds
      uses: actions/cache@v4
      id: nuget-cache
      with:
        path: |
          ~/.nuget/packages
          ${{ github.workspace }}/**/obj/project.assets.json
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          ${{ runner.os }}-nuget-

    - name: Restore with dotnet
      run: dotnet restore
      shell: pwsh

    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore --no-incremental
      shell: pwsh